name: Issue Opened Trigger

on:
  issues:
    types: [opened]
  issue_comment:

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "I'm running"
